name: Build and Test PR when labeled

on:
  pull_request:
    types: [ labeled ]

jobs:
  remove-build-label:
    uses: canonical/inference-snaps-dev/.github/workflows/remove-label.yaml@v2
    with:
      label: ${{ vars.PR_BUILD_TRIGGER_LABEL }}
  
  remove-test-label:
    uses: canonical/inference-snaps-dev/.github/workflows/remove-label.yaml@v2
    with:
      label: ${{ vars.PR_TEST_TRIGGER_LABEL }}

  build-pre-check:
    name: Build pre-check
    if: ${{ github.event.label.name == vars.PR_TEST_TRIGGER_LABEL }}
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build-pre-check.outputs.build-success }}
    steps:
      - id: build-pre-check
        name: Check for existing successful build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_NAME: "Build and Test PR when labeled"
        run: |
          # exit with non-zero code if any command fails, if any variable is unset, or if any command in a pipeline fails
          set -euo pipefail

          commit_sha="${{ github.event.pull_request.head.sha }}"
          successful_runs_count="$(gh run list \
            --repo "${{ github.repository }}" \
            --commit "$commit_sha" \
            --json conclusion,workflowName \
            --jq '[.[] | select(.conclusion == "success" and .workflowName == env.WORKFLOW_NAME)] | length')"

          if [ "$successful_runs_count" -gt 0 ]; then
            echo "Found successful run(s) for commit $commit_sha"
            echo "build-success=true" >> "$GITHUB_OUTPUT"
          else
            echo "No successful runs found for commit $commit_sha"
            echo "build-success=false" >> "$GITHUB_OUTPUT"
          fi
  build-and-publish:
    needs: [build-pre-check]
    if: always() && ((github.event.label.name == vars.PR_BUILD_TRIGGER_LABEL) || (github.event.label.name == vars.PR_TEST_TRIGGER_LABEL && needs.build-pre-check.outputs.build-success == 'false'))
    uses: canonical/inference-snaps-dev/.github/workflows/build-publish-snap.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ self-hosted, amd64, noble, large ]
          - [ self-hosted, arm64, noble, large ]
    with:
      runner: "${{ toJSON(matrix.runner) }}"
      init-build-script: 'prepare-models.sh'
      # Publish to a channel with the pr number in it
      publish-channel: latest/edge/pr-${{ github.event.pull_request.number }} # Add track if needed, e.g., 24/latest/edge/pr-#
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN }}
  
  test:
    if: ${{ github.event.label.name == vars.PR_TEST_TRIGGER_LABEL }}
    uses: ./.github/workflows/testflinger-tests.yaml
    with:
      snap-channel: latest/edge/pr-${{ github.event.pull_request.number }}

