name: Build+Test PR

on:
  pull_request:
    types: [ labeled ]

jobs:
  remove-build-label:
    uses: canonical/inference-snaps-dev/.github/workflows/remove-label.yaml@v2
    with:
      label: ${{ vars.PR_BUILD_TRIGGER_LABEL }}
  
  remove-test-label:
    uses: canonical/inference-snaps-dev/.github/workflows/remove-label.yaml@v2
    with:
      label: ${{ vars.PR_TEST_TRIGGER_LABEL }}

  build-pre-check:
    if: ${{ github.event.label.name == vars.PR_TEST_TRIGGER_LABEL }}
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build-pre-check.outputs.build-success }}
    steps:
      - id: build-pre-check
        name: Check for existing successful build
        uses: canonical/inference-snaps-testing/.github/actions/build-pre-check@IENG-2278-testing-workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          workflow-name: ${{ github.workflow }}

  build-and-publish:
    # This dependency ensures that build-and-publish runs after build-pre-check finishes.
    needs: [build-pre-check]
    # Normally, build-and-publish would be skipped if build-pre-check is skipped because it depends on it.
    # always() is added so build-and-publish still runs when build-pre-check is skipped,
    # for example when PR_BUILD_TRIGGER_LABEL is added.
    if: always() && ((github.event.label.name == vars.PR_BUILD_TRIGGER_LABEL) || (github.event.label.name == vars.PR_TEST_TRIGGER_LABEL && needs.build-pre-check.outputs.build-success == 'false'))
    uses: canonical/inference-snaps-dev/.github/workflows/build-publish-snap.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ self-hosted, amd64, noble, large ]
          - [ self-hosted, arm64, noble, large ]
    with:
      runner: "${{ toJSON(matrix.runner) }}"
      init-build-script: 'prepare-models.sh'
      # Publish to a channel with the pr number in it
      publish-channel: latest/edge/pr-${{ github.event.pull_request.number }} # Add track if needed, e.g., 24/latest/edge/pr-#
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN }}
  
  test:
    # This dependency ensures that test runs after build-and-publish finishes.
    needs: [build-and-publish]
    # always() is added so test still runs when build-and-publish is skipped, for example when build-pre-check finds an existing successful build and skips build-and-publish.
    if: ${{ always() && github.event.label.name == vars.PR_TEST_TRIGGER_LABEL && (needs.build-and-publish.result == 'success' || needs.build-and-publish.result == 'skipped') }}
    uses: ./.github/workflows/testflinger-tests.yaml
    with:
      snap-channel: latest/edge/pr-${{ github.event.pull_request.number }}

