#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.install"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

#
# Set generic config
#

modelctl set --package verbose="false"

# Main server http config
modelctl set --package http.port="8328"
modelctl set --package http.host="127.0.0.1"

# Webui server config
modelctl set --package webui.http.port="8329"
modelctl set --package webui.http.host="127.0.0.1"


#
# WSL workaround
#
# With a layout we bind $SNAP_COMMON/usr/lib/wsl to /usr/lib/wsl.
# The layout automatically creates the source directory if it does not exist.
# We then create symlinks in this dir for the lib and drivers subdirectories,
# so they appear at /usr/lib/wsl/lib and /usr/lib/wsl/drivers in the layout.
ln -s /var/lib/snapd/hostfs/usr/lib/wsl/lib $SNAP_COMMON/usr/lib/wsl/lib
ln -s /var/lib/snapd/hostfs/usr/lib/wsl/drivers $SNAP_COMMON/usr/lib/wsl/drivers

#
# Auto select an engine
#

if snapctl is-connected hardware-observe; then
    modelctl use-engine --auto --assume-yes
elif lscpu -V &> /dev/null; then
    echo "Able to access hardware info without hardware-observe interface connection: assuming dev mode installation."
    modelctl use-engine --auto --assume-yes
else
    echo "hardware-observe interface not auto connected. Skip auto engine selection."
fi
